# Promises experiment

---

Copy this code :

```js
const fakeCallToAnAPIPromises = (url) => {
  return new Promise((resolve, reject) => {
    const delay = Math.floor(Math.random() * 4500) + 500;
    setTimeout(() => {
      if (delay > 4000) {
        reject("Connection Timeout ! :(");
      } else {
        resolve(`Here is your fake data from ${url}`);
      }
    }, delay);
  });
};
```

It's exactly the same simulation, but this time the function to call the API returns a `promise` object. The `promise` object already has a `resolve` and `reject` callback method, so we don't need to expect them in our `fakeCallToAnAPIPromises` function.

Let's do the same thing we did but with promises :

```js
fakeCallToAnAPIPromises("api/movies")
  .then((data) => {
    console.log("SUCCESS (1)");
    console.log(data);
    return fakeCallToAnAPIPromises("api/movies/7");
  })
  .then((data) => {
    console.log("SUCCESS (2)");
    console.log(data);
    return fakeCallToAnAPIPromises("api/pictures/7");
  })
  .then((data) => {
    console.log("SUCCESS (3)");
    console.log(data);
  })

  .catch((error) => {
    console.log(error);
  });
```

Test it ! ;)
It's the same as before ! We just changed a little bit the syntax in a much simpler way with promises.

(the `catch` method will run if there is an error)

We only have one callback per step.

---

Let's try to recap...

- A `promise` is an object. This object has several properties like : the status of the request, the value of the request (when it's successfully completed) and some methods like `then` (that will take a callback to continue the code after the promise is resolved sucessfully) and `catch` (that will take a callback to handle the error that happened)

- The callback of the `then` method receives the result of the promise (like the list of movies)
- The callback of the `catch` method receives the result as well in case of error (a message 404 from the server for example)
- If in a `then` callback we return another promise, we can chain from one promise to the other with the `then` method.

Practically, what we've done is something like this :

- We called `api/movies`
  - If it's a success, we receive `then` the response as parameter of the callback
  - If it's failure, we go directly to the `catch` callback

Let's say it's a success..

- We received back the list of movies (it's where there is the `SUCCESS (1)` log)
- From this list, we want the movie with ID 7. So we called the API one more time. (returning a promise in the callback)
- Same thing: we got back the infos of the movie 7
- And then we called the api one more time to get the pictures of this movie.

![](https://media.giphy.com/media/7E8UUn3jg36aDEWdBO/giphy-downsized.gif)

---

Let's watch these videos to brute force our comprehension :

[Promises in 100 seconds](https://youtu.be/RvYYCGs45L4?si=5mvdhugPlmHHoJod)
[Promises in 20 minutes](https://youtu.be/novBIqZh4Bk?si=mBhSP9339trvjrsS)

[Promises in french](https://www.youtube.com/watch?v=SSYt7C4sCbw&ab_channel=DevTheory)
